### ISSUE TITLE
Update ember-cli-babel dependency

### ISSUE THREAD

**Issue by steveszc** [DockYard/ember-service-worker#101]
The ember-cli-babel dependency should be updated to the latest version to allow consuming apps to drop ember-cli-shims as a dependency of ember 2.16+ apps.
https://www.emberjs.com/blog/2017/11/20/ember-2-17-released.html#toc_changes-in-ember-cli-2-17

**Comment by broerse** [comment]
@martndemus can we do @YoranBrondsema fix to get around the babel deprecation?

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: myapp -> ember-service-worker -> ember-cli-babel
```

**Comment by NullVoxPopuli** [comment]
I'd also love this update. It'll allow me to shave ~ 3KB off my bundle. :-)

**Comment by thstarshine** [comment]
any update on this?

**Comment by alexmasita** [comment]
Would be nice to have this update ...

**Comment by eshtadc** [comment]
The dependency update has been merged. I would expect an updated release pretty soon.
