### ISSUE TITLE
Allow relative sw.js registration

### ISSUE THREAD

**Issue by zorn-v** [DockYard/ember-service-worker#111]
Currently it is imposible. But in ember if no rootURL is defined assets inserted with relative url.
I think "last resort" should be '' but not '/' here https://github.com/DockYard/ember-service-worker/blob/master/index.js#L144

PS. I have a project with no deterministic root url. Just imagine a 'skel' with symlinks to it, and logic depends of result url.
Anyway I implemented SW by my own (with 'scope':'./'), but it is big mistake to restrict relative urls...

**Comment by villander** [comment]
@zorn-v use `navigator.serviceWorker.register('/sw.js')` it's works as `./`

**Comment by zorn-v** [comment]
Nope.
Imagine that my index.html in https://example.com/subdir/another/
If I register as you say sw.js will try to load from https://example.com/sw.js (but it is not there)

**Comment by deepflame** [comment]
Our case sounds similar to yours.

We use the lightning deployment strategy and host our assets on a CDN. Now when we serve the index.html './sw.js' is not found as this is on the CDN.
If I change now the rootUrl in the config the scope points to the CDN but I would like it to remain '/'.

So we should be able to have a different configuration option for scope and URL of the sw.js file:
https://github.com/DockYard/ember-service-worker/blob/master/service-worker-registration/index.js#L7

**Comment by martndemus** [comment]
Service Workers need to be hosted on the same domain. CDN's are not allowed.
You'll need to adjust your lightning deploy system to deploy `sw.js` to the same box as the `index.html` file.

**Comment by deepflame** [comment]
Thanks for the clarification @martndemus . Maybe this is something for the docs as well?

**Comment by sescobb27** [comment]
There is some work in progress being made in `ember-cli-deploy-lightning-pack`, for now, we can follow the recommendations mentioned in this issue https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/issues/46 to deploy sw.js to the same host as the index.html

**Comment by achambers** [comment]
Another approach I have used in the lighting strategy, instead of hosting the service worker in the same place as index.html, is to simply have the lightning server forward the request for sw.js to the CDN

**Comment by eshtadc** [comment]
Good general information in here but nothing actionable that I see so closing this out.

**Comment by zorn-v** [comment]
> but nothing actionable
Really ? Remove slash and add ONE DOT with no drawbacks and many buns ?
Ok, you wish.

**Comment by eshtadc** [comment]
Hi there @zorn-v. It's quite possible that I've missed something here, so if you'd like to further explain - or submit a PR with your suggestion I'd be happy to look further and/or re-open this issue.
