### ISSUE TITLE
Safari Version 11.1 (13605.1.33.1.2) is bombing out with ember SW apps

### ISSUE THREAD

**Issue by bcardarella** [DockYard/ember-service-worker#117]
Examples: https://dockyard.com, https://hightide.earth

Steps to reproduce:

1. Use Safari 11.1
2. Clear caches
3. Visit either app from above

You will see something like

![screen shot 2018-05-26 at 6 20 31 pm](https://user-images.githubusercontent.com/18524/40580685-91b81530-6111-11e8-83bc-0328946513d4.png)

If you disable Service Workers the apps load as expected. This issue appears to be resolved in the WebKit nightly, however other Service Worker enabled apps that aren't ember-service-worker are not having this problem which leads me to believe that this is somehow isolated to esw.

Unfortunately Safari is not giving any additional information than the screen shot from above. There is nothing in the console or the network tab that may explain why this extreme error is happening.

This feels like a critical bug and should be prioritized, even though future versions of WebKit appear to be working this is a current production issue for all esw enabled apps with Safari visitors.

**Comment by brzpegasus** [comment]
This is resolved with [`ember-service-worker-index@0.6.7`](https://github.com/DockYard/ember-service-worker-index/pull/13).

**Comment by brzpegasus** [comment]
Reopening, since the fix introduced in https://github.com/DockYard/ember-service-worker-index/pull/13 had some undesired side effects.

**Comment by brzpegasus** [comment]
New fix available via [`ember-service-worker-index@0.6.9`](https://github.com/DockYard/ember-service-worker-index/pull/15)
