### ISSUE TITLE
Is there a way to have a custom service worker communicate with the ember app?

### ISSUE THREAD

**Issue by NullVoxPopuli** [DockYard/ember-service-worker#120]
Let's say I want to have a service worker control a websocket or webRTC connection -- could I have my ember app push messages to the service worker, and receive messages back from it so I can interact with ember-data?

I'm wanting to use a service worker for a persistent background connection on mobile devices. I know Web Workers have pushing of messages between scripts, but I don't know if they keep running when the app is not in focus / closed.

**Comment by NullVoxPopuli** [comment]
does that keep the service workers active / scripts running even when the app isn't open? (say I go look at twitter or something and my e-s-w powered app isn't in focus)

**Comment by anlumo** [comment]
Sometimes. It's way too complicated to explain here and outside the scope of ember-service-worker.

Here's an introduction to the concept itself: https://developers.google.com/web/fundamentals/primers/service-workers/

As far as I can see, there are two features that work when the web page is not open, [push notifications](https://developers.google.com/web/fundamentals/push-notifications/) and [background sync](https://developers.google.com/web/updates/2015/12/background-sync). Maybe there's more I missed.

**Comment by NullVoxPopuli** [comment]
thanks!
