### ISSUE TITLE
ember-cli-babel deprecation warning

### ISSUE THREAD

**Issue by matthooks** [DockYard/ember-service-worker#121]
Hi guys,

ember-source@3.2.1
ember-cli@3.1.3
ember-data@3.1.1
ember-service-worker@0.6.13
ember-service-worker-asset-cache@0.6.3

Just wanted to let you know I'm getting the following deprecation message using the above versions:

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: (project name redacted) -> ember-service-worker -> ember-cli-babel
```

Figured I'd start an issue so you can track the fix. No rush! Thanks for a great plugin.

**Comment by eshtadc** [comment]
Closing as this is a duplication of https://github.com/DockYard/ember-service-worker/issues/101
