### ISSUE TITLE
Bump ember-cli-babel version to avoid DEPRECATION warnings every build

### ISSUE THREAD

**Issue by josiahbryan** [DockYard/ember-service-worker#126]
Getting the following warning every time I build with `ember-service-worker` installed:

`
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ncs -> ember-service-worker -> ember-cli-babel
`

Can you bump the `ember-cli-babel` version to "at least 6.6" in your `package.json` so ember stops complaining when I use this addon? :) Thanks so much!

**Comment by Frozenfire92** [comment]
It seems to already be in the package.json

I suspect a new version needs to be released and that should fix the issues

**Comment by josiahbryan** [comment]
Ahhh my apologies, I didn't actually check your GitHub source of that file.
I can try installing right from GitHub instead of using npm.

Any idea of when a new release will come out?

**Comment by alanlalonde** [comment]
Same question here, I guess this issue isn't so much about fixing the problem in code, but rather requesting a new published release?

**Comment by raphaelns-developer** [comment]
I'm waiting for this release as well. Can you please publish it to stop the warning?

**Comment by iurikothe** [comment]
+3 :-)

**Comment by eshtadc** [comment]
New version has been published (0.7.0). Sorry for the delay. I was hoping to get a few other dependencies updated, but I'll continue to work on that for a follow-up patch release.
