### ISSUE TITLE
Build Error (UglifyWriter)

### ISSUE THREAD

**Issue by ming-codes** [DockYard/ember-service-worker#128]
```
Build Error (UglifyWriter)

Unexpected token: name (SUCCESS_HANDLERS)
```

I did some investigation and found that it could be this `broccoli-uglify-sourcemap@1.5.2`. I believe this version is still using uglifyjs where it doesn't recognize ES6 syntax.

`ember-cli-uglify` has migrated to using terserjs, where it's a fork of uglifyjs that can recognize new ES6 syntax.

Please consider upgrading to the latest `2.2.0`

**Comment by rmmmp** [comment]
I'm also seeing this issue. I have to downgrade to `0.6.12` to get things working.
