### ISSUE TITLE
Service Worker registration failed with TypeError: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by zubeirtech** [DockYard/ember-service-worker#163]
The error: ``` Service Worker registration failed with TypeError: Failed to register a ServiceWorker for scope ('http://localhost:4200/%7B%7BROOT_URL%7D%7D') with script ('http://localhost:4200/%7B%7BROOT_URL%7D%7D%7B%7BSERVICE_WORKER_FILENAME%7D%7D'): A bad HTTP response code (404) was received when fetching the script. ```

My application is not able to register the serviceworker and I am receiving the error that it's not finding the sw.js file. I created a new project and installed all the dependencies for making the website a pwa, just to check if my application was the fault and i still received the error with the ember welcome page app

 [here is the repo](https://github.com/zubeirtech/pwa)

I looked at the sw-registration.js file and found this

``` 
navigator.serviceWorker.register('{{ROOT_URL}}{{SERVICE_WORKER_FILENAME}}', {
```
code part which might cause this error, since it doesn't find the sw.js file

**Comment by viniciussbs** [comment]
Same thing here. I was facing #125 - I was using an old version of this addon - and updated to v0.8.3 since the issue was fixed. Now I'm facing this one. I rolled it back to v0.8.0 and it's working again.

**Comment by zubeirtech** [comment]
Yes, in v0.8.3 the sw-registration is using ```  navigator.serviceWorker.register('/sw.js', {
      scope: '/'
    }) ``` to register the service worker. Had to rollback to it too so it works

**Comment by devotox** [comment]
Yup getting this as well on 0.8.3

**Comment by eshtadc** [comment]
I am able to reproduce this. Thank you for reporting. I'm looking into a fix...

**Comment by eshtadc** [comment]
Looks like this is caused by version 2.3.1 of `@rollup/plugin-replace` which was released 13 days ago. It's a dependency upgrade and I haven't nailed down the full case yet. In the meantime, we peg our dependency here until it is sorted out. Thanks all for reporting!

**Comment by keerthanakottapalli** [comment]
in.ts:6 Service worker registration failed with: TypeError: Failed to register a ServiceWorker for scope ('http://localhost:59968/') with script ('http://localhost:59968/ngsw-worker.js'): A bad HTTP response code (404) was received when fetching the script.
