### ISSUE TITLE
Document `addEventListener` in README.

### ISSUE THREAD

**Issue by rwjblue** [DockYard/ember-service-worker#17]
Looks like `self.addFetchListener` is used in the various pre-built plugins, but is not documented in the README so I am unsure if this is intended as public API or just an internal private API for use by "first party" addons.

**Comment by martndemus** [comment]
Yes this was intended as public api. I just forgot to document it.

**Comment by NekR** [comment]
What is wrong with regular `fetch` addEventListener?

**Comment by martndemus** [comment]
You can only `event.respondWith` once. So if you would add multiple `addEventListener('fetch')`, then either (depending on implementations):
- The first listener will always respond and further listeners will never be called
- All listeners are executed at the same time and then you have a race condition.

`self.addFetchListener` calls each listener one by one. It will call `respondWith` when a listener resolves to a response and not further call any other listeners.

See: https://github.com/slightlyoff/ServiceWorker/issues/836#issuecomment-187246291

**Comment by NekR** [comment]
I see, thanks.

So you say some browsers has wrong implementation  where `fetch` event may race? Do you know which browsers and maybe you know the bug I'd in their tracker?

**Comment by martndemus** [comment]
No, that is by design in the Service Worker spec.

**Comment by NekR** [comment]
So then it's a bug in those browsers which fire fetch events one by one? I
really doubt that spec specifies 2 behaviors for the same thing.
