### ISSUE TITLE
Allow project to have `service-worker/` folder (and act the same as an addon).

### ISSUE THREAD

**Issue by rwjblue** [DockYard/ember-service-worker#18]
This would allow for small project level tweaks/experimentation to be done in the project itself.

**Comment by martndemus** [comment]
👍

**Comment by AKST** [comment]
Is this still applicable for the most recent version of this plugin? I can't find any documentation on this...

**Comment by martndemus** [comment]
Yes.

Let me know if it doesn't

**Comment by AKST** [comment]
Well I can't seem to locate the documentation on this feature (maybe I missed this), & from poking through this issue & the associated PR I gathered some insight on how this works if this functionality is still available, but I couldn't seem to figure it out.
