### ISSUE TITLE
service worker asset caching will blink landing page when on non-landing page

### ISSUE THREAD

**Issue by bcardarella** [DockYard/ember-service-worker#22]
See: https://www.youtube.com/watch?v=1V10bgdIp2M

When the service worker is running and assets are cached a reload of a non-landing page will cause the app landing page to blink. Deleting the service worker temporarily fixes the problem but after the assets are cached again the problem is back.

I don't know if this is an actual service worker issue or how Ember is rendering based upon available assets.

**Comment by martndemus** [comment]
@bcardarella This must be because it caches `/index.html` as fallback, which I suspect is being rendered by fast boot.

**Comment by bcardarella** [comment]
Ah, yes that makes sense. How should we work around this?

**Comment by martndemus** [comment]
Delete the `else if` statement in the fetch hook of ember-service-worker-asset-cache is step 1. Step 2 is find out how serve a proper index.html when the page hasn't been visited before
