### ISSUE TITLE
Use `rootURL` for service worker registration scope.

### ISSUE THREAD

**Issue by rwjblue** [DockYard/ember-service-worker#27]
This is somewhat related to https://github.com/DockYard/ember-service-worker/issues/14, but we need to expose the running applications `rootURL` and use that for the service worker scope.

Specifically, [this line](https://github.com/DockYard/ember-service-worker/blob/09dce3df1869bee4ba04b7c8ae8572d31440e31c/lib/registration.js#L3) needs to have access to the config and use the specified `rootURL`.

**Comment by martndemus** [comment]
Confirm
