### ISSUE TITLE
RFC: Make registration pluggable.

### ISSUE THREAD

**Issue by rwjblue** [DockYard/ember-service-worker#31]
Extract `lib/registration.js` to live inside of a plugin.  This will allow various configurations for registration.

One specific example that I need/want is to be able to check the service worker after installation to ensure that it matches the running application. This prevents massive self-trollage when developing applications locally where a service worker could have been registered for `http://localhost:4200` by `project-a`, then you switch to `project-b` and you are completely hosed. I have a working prototype of this [in this branch](https://github.com/DockYard/ember-service-worker/compare/master...rwjblue:prototype-paired-registration), but if I have a different registration then I would imagine that others may as well.  

If there are no objections, I'll extract the current registration system into `ember-service-worker-basic-registration` and my version into `ember-service-worker-project-entangled-registration` (naming sucks).

**Comment by martndemus** [comment]
I don't see your PR solving this in a good way. 
I wouldn't like it if I had to rewrite the whole registration code manually. I think we should again be able to define some code and then call it when the registration resolves.

For example:

```js
{{USERLAND_CODE}}

if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('{{ROOT_URL}}sw.js', { scope: '{{ROOT_URL}}' })
    .then(function(reg) {
      {{RUN_USERLAND_SUCCES_HANDLERS}}
    })
    .catch(function(error) {
      {{RUN_USERLAND_ERROR_HANDLERS}}
    });
}
```

Later this should be combined with being able to register multiple service workers at different scopes.

**Comment by rwjblue** [comment]
Seems good, my PR can easily be modified to provide a `addRegistrationSuccessHandler`. But it still needs to be a separate tree, which is what the majority of the code actually does...

**Comment by martndemus** [comment]
Yes, I didn't mean to criticise the extra tree, just the way you had to fully write the registration code.

**Comment by rwjblue** [comment]
No worries, working on refactoring to allow registration of callbacks.

**Comment by martndemus** [comment]
Awesome!
