### ISSUE TITLE
Issue registering service worker

### ISSUE THREAD

**Issue by piotrpalek** [DockYard/ember-service-worker#42]
@martndemus would you mind cutting a bugfix release with these: https://github.com/DockYard/ember-service-worker/commit/f13a7e0c9a3ecda79fe8e96e7c75b6c20e0331c6#diff-65a8cac6085d6a16feee20105f04e29f changes? I'm getting an error when the service worker is trying to register.

**Comment by TameBadger** [comment]
same here

**Comment by martndemus** [comment]
Published `0.5.1`

**Comment by piotrpalek** [comment]
thanks I'll close this issue since it fixed my problem :+1:
