### ISSUE TITLE
still unsafe?

### ISSUE THREAD

**Issue by ksnyde** [DockYard/ember-service-worker#44]
Is the statement on the README still the situation?

> Do not use this in production right now, you will troll your users and they will be unable to use your app.

If it is, is there any feeling for a rough timeframe this might be addressed?

**Comment by martndemus** [comment]
My current stance is: I'd suggest you install it and test it on your staging environment.
If it doesn't work I'll try my best to get it working for you within the time I can dedicate for it.

**Comment by martndemus** [comment]
I'll update the README with this message

**Comment by ksnyde** [comment]
Ok thanks @martndemus. Should we close this?

**Comment by martndemus** [comment]
Yep!
