### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by beatrizdemiguelperez** [DockYard/ember-service-worker#45]
I installed:
ember install ember-service-worker-asset-cache
ember install ember-service-worker-cache-fallback
ember install ember-service-worker-cache-first

First: 
404 Not Found GET http://localhost/sw.js 
404 Not Found GET http://localhost/sw-registration.js 

Changing 
        <script src="/sw-registration.js"></script>
to 
        <script src="sw-registration.js"></script>

and changing     navigator.serviceWorker.register('/sw.js',  without /

I don't have my dist folder served at localhost/

Running ember serve:
No name was provided for external module 'ember-service-workers/service-worker' in options.globals – guessing 'emberServiceWorkers_serviceWorker'

New error :S

**Comment by martndemus** [comment]
Please try again with the newest version!
