### ISSUE TITLE
Flag to disable?

### ISSUE THREAD

**Issue by oskarrough** [DockYard/ember-service-worker#70]
Hi, is there an environment flag or similar that could kill the service-worker?

Working with a service-worker in development isn't always fun :)

**Comment by bcardarella** [comment]
even if we added one, you'd have to kill the SW in your browser or force a hard reload.

One alternative could be if we "disable" he SW it just renders out a `sw.js` with a simple unregister?

**Comment by bcardarella** [comment]
There could be two ways to do this:

1. env var: `EMBER_SERVICE_WORKER=false ember s`
2. query params: `http://localhost:4200/posts?sw=false`

this would mimic a similar disable API that ember-cli-fastboot is adding: https://github.com/ember-fastboot/ember-cli-fastboot/commit/d01c3f6cb15223570505e46a6b4ef67023c0e75e

**Comment by jakeleboeuf** [comment]
I support this :) 

Unregistering the SW in the browser is not a big deal. It get's pretty annoying having to *always* have the console open.

**Comment by simonihmig** [comment]
We have done that using ember-cli's blacklist feature:

```js
/// ember-cli-build.js
  let disabledAddons = [];
  if (EmberApp.env() !== 'production' && !process.env.ENABLE_SW) {
    // disable service workers by default for dev and testing
    disabledAddons.push('ember-service-worker');
  }

let app = new EmberApp(defaults, {
    addons: {
      blacklist: disabledAddons
    },
   ...
});
```
