### ISSUE TITLE
Feature Request : Fastboot index.html

### ISSUE THREAD

**Issue by The-Don-Himself** [DockYard/ember-service-worker#77]
Following the guidelines for a feature request:

**What will it allow you to do that you can't do today?**
This feature request would allow the service worker to use the fastboot generated index.html where fastboot environments are enabled.

**Why do you need this feature and how will it benefit other users?**
I need this feature for my fastboot powered ember [app](https://campus-discounts.com), on first load users immediately see something as the emberjs libraries are downloaded. After installing the (awesome) ember-service-worker users see a blank white page which is the default index.html for a long time (~3 secs desktop, 10+ secs mobile). This feature request will benefit me and others speed up the performance perception of our app to users.

**Are there any drawbacks to this feature?**
Not that I can think of.

**Comment by martndemus** [comment]
Please open this issue against https://github.com/dockyard/ember-service-worker-index

**Comment by The-Don-Himself** [comment]
You are right, thanks! Moving issue now, plus perhaps a better title such as customizing index.html.

**Comment by The-Don-Himself** [comment]
Matter of fact, I think this issue should be permanently closed as the referenced [ember-service-worker-index](https://github.com/DockYard/ember-service-worker-index) allows selecting the index.html, I think I can build on this feature from there thanks.
