### ISSUE TITLE
Will not allow empty sting as rootURL 

### ISSUE THREAD

**Issue by kylemellander** [DockYard/ember-service-worker#82]
in the index.js, it finds the settings for the rootURL.  However, it only looks to see if they are truthy or not.  So for an app that has its rootURL at `''`, it actually sets it to `'/'`

**Comment by martndemus** [comment]
This is actually a thing in Ember ¯\_(ツ)_/¯

**Comment by engwan** [comment]
Actually, ember now accepts empty string as rootURL.

I'm also having trouble with this with a cordova app that expects rootURL to be `''`.

Reference here: https://github.com/ember-cli/ember-cli/pull/6182
