### ISSUE TITLE
Force SW update on refresh/boot

### ISSUE THREAD

**Issue by benoror** [DockYard/ember-service-worker#83]
According to this [Google documentation regarding the SW lifecycle](https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/lifecycle) sw updates are checked once every 24 hours. Is there a way to force the update and/or changing the `max-age` value?

**Comment by bcardarella** [comment]
you can tie your SW to a version or git commit to force it to expire. We use our package.json version value for dockyard.com

**Comment by benoror** [comment]
Thanks @bcardarella! I guess you mean manually triggering `navigator.serviceWorker.register` right? I can see doing this in different programmatic ways. We currently check for our latest git commit hash to prompt the user to refresh the page, I guess we can substitute refreshing for updating the SW... pretty straightforward 😄 

Just wondering how do you handle it in dockyard.com using package.json version? Do you have a code snippet/addon?

Regards!

**Comment by bcardarella** [comment]
this addon has those strategies built in: https://github.com/DockYard/ember-service-worker/blob/2b42ecc0f257d59be595268078e78d4f2d9ab60a/lib/index-file.js#L15-L17

**Comment by benoror** [comment]
@bcardarella awesome! We might consider `versionStrategy: 'every-build'` as well

Thanks!

**Comment by bcardarella** [comment]
:+1:

**Comment by benoror** [comment]
Cross refference (pls ignore): Handle SW updates correctly - https://github.com/ecaresoft/nimbox/issues/572
