### ISSUE TITLE
CSS Hot Reload is Broken

### ISSUE THREAD

**Issue by devotox** [DockYard/ember-service-worker#84]
When using Ember service worker anytime a scss file changes sw.js changes and i think this causes a full page reload

```
Build successful (4967ms) – Serving on http://localhost:8088/
  ember-cli:live-reload: files %a [ 'index.html', 'sw.js', 'tests/index.html' ] +19m
```

**Comment by martndemus** [comment]
Closing in favor of #88

**Comment by jrjohnson** [comment]
Workaround if anyone needs it. When working with styles in a service worker enabled site I just add use ENV variable:
`SW_DISABLED=true`
Worker is disabled and Hot Reload is restored.
