### ISSUE TITLE
Errors only after deploy

### ISSUE THREAD

**Issue by broerse** [DockYard/ember-service-worker#93]
I am testing this addon on https://bloggr.exmer.com but each time I deploy I also have to clear the SW in Chrome before the Bloggr App works again. Since there are no issues reported on this behavior I was wondering if someone can hint where to look. Source: https://github.com/broerse/ember-cli-blog

**Comment by martndemus** [comment]
Have you tried `every-build` according to: http://ember-service-worker.com/documentation/configuration/#versioning ?

**Comment by broerse** [comment]
No I didn't. That is probably it. Thanks. Will close this issue for now.

**Comment by broerse** [comment]
It worked!!!

**Comment by martndemus** [comment]
Great!
