### ISSUE TITLE
How to configure path to sw.js when using CDN

### ISSUE THREAD

**Issue by kjf** [DockYard/ember-service-worker#97]
Using ember-cli-deploy I'm fingerprinting my assets and prefixing with `https://subdomain.cloudfront.net`.

I understand fingerprinting sw.js will break the service worker update mechanism so it makes sense to disable fingerprinting that file, however I would still like it to retain the CDN prefix.
Can anyone recommend the best way to do this?

**Comment by martndemus** [comment]
@kjf AFAIK it's not possible to load a Service Worker from a different domain at this moment.

**Comment by kjf** [comment]
Makes sense. Cheers.
