### ISSUE TITLE
Allow url patterns from other origins

### ISSUE THREAD

**Issue by dylanitorium** [DockYard/ember-service-worker#98]
Hi there,

The issue I'm facing is actually with the `ember-service-workers-cache-fallback` package, but the utils originate here.

Currently, all the patterns provided in the EmberApp configuration are mapped with `createUrlRegEx` from the `ember-service-workers` package. As part of `createUrlRegEx` the pattern is then passed through `createNormalizedUrl` which, by default, prepends the url with the baseUrl of `self.location`. This effectively means it will only cache responses from the same origin.

In some projects, and in development an api call will be made to a different origin but in this case it cannot be cached with this addon. 

Would we be able decouple `createUrlRegEx` from `createNormalizedUrl` so there is less restriction on api response caching?

Let me know if you would not like this to happen otherwise, I'm happy to submit a PR for it. 

Cheers!
Dylan

**Comment by simonihmig** [comment]
@dylanitorium afaict `baseUrl` is only used when the URL is relative, with an absolute URL it should be ignored. See https://developer.mozilla.org/en/docs/Web/API/URL/URL.

I have this in an app, and this is working fine:

```js
'esw-cache-fallback': {
      patterns: [
        // cache api requests, excluding auth (handled separately)
        `${apiHost}/api/(?!auth-ping)(?!logout)(?!login)(?!authcode).+`
      ]
    }
```

**Comment by dylanitorium** [comment]
Oh right, that makes total sense! It didn’t occur to me to just put the host into the patterns. I’ll give that a try.

Thanks!
