### ISSUE TITLE
Uncaught ReferenceError: ESW_INLINE_PLACEHOLDER is not defined

### ISSUE THREAD

**Issue by davidbilling** [DockYard/ember-service-worker#99]
When I set registrationStrategy to inline, my test fails with:

"Uncaught ReferenceError: ESW_INLINE_PLACEHOLDER is not defined"

My config:

    'ember-service-worker': {
      enabled: true,
      versionStrategy: 'every-build',
      registrationStrategy: 'inline'
    },
Ember-cli 2.17.1

**Comment by rwwagner90** [comment]
I also randomly just started seeing this.

**Comment by davidbilling** [comment]
Update @rwwagner90 I have updated to Ember-cli 3.0.0 and ember-service-worker 0.6.11 and it is still there. 
My quickfix is to comment out registrationStrategy when testing and uncomment on release.

**Comment by rwwagner90** [comment]
@davidbilling it's odd I never saw this before though. I made some changes to ember-service-worker-prember and all the sudden got this.

**Comment by rwwagner90** [comment]
@martndemus any ideas on this? I'm still unable to use inline.

**Comment by davidbilling** [comment]
@cyk @martndemus I see this fix for this is merged and alot of other things, will there be a new release soon?

**Comment by marten-dockyard** [comment]
Released 0.6.13

**Comment by davidbilling** [comment]
@marten-dockyard Big thanks!
